<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_3243632547</name>
   <tag></tag>
   <elementGuidId>3fb0a772-822a-4a1c-9c64-759f94e2e31e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='toAccountId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toAccountId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>50e6248b-8ac6-4f92-8918-7c5631aa619d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toAccountId</value>
      <webElementGuid>82de7a0d-4885-4cf7-85e7-977c5714895e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>3a6186b6-7c88-4e49-8d14-1ba370705c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>accounts.toAccountId</value>
      <webElementGuid>68b36780-0366-434d-a675-e5236209445a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>account.id for account in accounts track by account.id</value>
      <webElementGuid>b40973d4-db57-48a1-a387-7235a8f79326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3243632547</value>
      <webElementGuid>0a171e6f-b2a6-40de-9134-cc568c2370d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toAccountId&quot;)</value>
      <webElementGuid>abb30205-805b-4b13-bf45-bcdd100f4fb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='toAccountId']</value>
      <webElementGuid>75eb8961-01df-44b5-b289-a2a2f024cf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/div/select[2]</value>
      <webElementGuid>2478dd25-18a0-40f0-b5a3-75fdbf1ae86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>91891d47-adcb-4712-a4c0-42c2fc34d6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'toAccountId' and (text() = '3243632547' or . = '3243632547')]</value>
      <webElementGuid>51b5bbee-cf2d-420d-839b-998605dea79c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
