<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_credentials.passcode</name>
   <tag></tag>
   <elementGuidId>d3ccd675-452c-49fc-a555-6d81a20b5aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input36']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input36</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea181238-56f8-42d5-95c5-cfa0997afbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>02da7048-211b-42de-bfec-05314064a502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>credentials.passcode</value>
      <webElementGuid>c75b8a2b-26dd-4afe-ab07-517dcf453cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input36</value>
      <webElementGuid>8ab69484-9b54-4d18-9ff5-f65aee15006e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>a23aed0c-06d1-484b-b8ee-44ea58e9351f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-with-toggle</value>
      <webElementGuid>dd5aa42b-7ce9-4a04-b7ad-60b6d9420599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input36&quot;)</value>
      <webElementGuid>9fb55023-40c7-4f2b-bec6-4f3e4f3f7605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input36']</value>
      <webElementGuid>e7c2bfcb-9d8b-4f15-abe0-b82b3da6bb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form20']/div/div[3]/div[2]/div[2]/span/input</value>
      <webElementGuid>f294188f-5848-4ff5-abf2-a99baebcff2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/input</value>
      <webElementGuid>75a5a185-b80a-42ed-b542-c49d42788cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'credentials.passcode' and @id = 'input36']</value>
      <webElementGuid>78e6faba-590d-40cc-84a0-e54651e3bdef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
