<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Keep me signed in</name>
   <tag></tag>
   <elementGuidId>da89c1b8-847d-4348-902d-57a6a0999fbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form20']/div/div[3]/div[3]/div/span/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9debf77b-5a6f-4ca5-b840-f834b1d72640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>input44</value>
      <webElementGuid>55074e73-85f3-4cb9-92f3-d3f9c47457a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-se-for-name</name>
      <type>Main</type>
      <value>rememberMe</value>
      <webElementGuid>edee4c2d-d9c6-4764-824c-1ba5324b26e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>e2753cd1-d33c-408d-9ed0-0b3caa0e24a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keep me signed in</value>
      <webElementGuid>8021490e-365d-4ecf-9ea4-2d0982fade66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form20&quot;)/div[@class=&quot;o-form-content o-form-theme clearfix&quot;]/div[@class=&quot;o-form-fieldset-container&quot;]/div[@class=&quot;o-form-fieldset o-form-label-top&quot;]/div[@class=&quot;o-form-input&quot;]/span[@class=&quot;o-form-input-name-rememberMe&quot;]/div[@class=&quot;custom-checkbox&quot;]/label[@class=&quot;hover&quot;]</value>
      <webElementGuid>2f9630fb-5e09-43f4-9559-1af6f0883d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form20']/div/div[3]/div[3]/div/span/div/label</value>
      <webElementGuid>029a2c06-503f-485c-8765-d475e6eb7e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/label</value>
      <webElementGuid>a2dd3781-87f8-4d12-88d3-56706513fa83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Keep me signed in' or . = 'Keep me signed in')]</value>
      <webElementGuid>9d81bbd7-362a-4475-b4a5-b6febe4a093a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
