<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Polis_searchDisplay</name>
   <tag></tag>
   <elementGuidId>22c2d8d8-78ed-4f7f-b5a6-0819dcf72886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchDisplay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchDisplay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2ea0901-5b31-4087-880b-390f64ee26f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDisplay</value>
      <webElementGuid>e95d1c48-54a1-4dd2-89a5-c6bfa7f8fdc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3eb6c3df-1f0d-468d-aee9-906d2730a563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>54b52baf-da41-4dd1-9fd7-10f752b18bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari dengan nama/kota</value>
      <webElementGuid>2e4fa379-52f4-4df7-8ab7-6b703b8e62b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Cari dengan nama/kota</value>
      <webElementGuid>385430c8-61ed-4e05-a12c-056aa9e9fea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Cari dengan nama/kota</value>
      <webElementGuid>3dde0cb7-1230-4af1-b802-a24e81be6302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchDisplay</value>
      <webElementGuid>6063f324-dc2a-494d-bec2-8a1ddb4238dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDisplay&quot;)</value>
      <webElementGuid>9c423f5b-9ec6-4144-901d-22b806a68094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchDisplay']</value>
      <webElementGuid>89d89500-67fa-4403-8aac-bdf561a1f6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/form/div[2]/input</value>
      <webElementGuid>b9549340-312f-4389-86d3-dc67216bf6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b1d96f62-a73e-49e2-ba94-82877e7a4996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchDisplay' and @type = 'text' and @placeholder = 'Cari dengan nama/kota' and @name = 'searchDisplay']</value>
      <webElementGuid>685c10dc-ffbe-4ba9-abe9-0681dac4fc68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
