<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buka DIGIF</name>
   <tag></tag>
   <elementGuidId>3e245988-1a21-4a34-a475-59787315b0d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.mt-4.sl-btn.d-flex</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2ef2b0d-59e4-4cd6-b8fc-40f8a5ff7674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9b4f67f-39a1-4277-af75-62247939b619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mt-4 sl-btn d-flex</value>
      <webElementGuid>22d375d2-6906-4396-b0a4-9792f50fe081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buka DIGIF</value>
      <webElementGuid>d73109d2-dd17-4fbc-ad70-a28298e53c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-modalDigifHome&quot;)/div[@class=&quot;modal-dialog position-relative&quot;]/div[@class=&quot;modal-content rounded-0&quot;]/div[@class=&quot;modal-body modal-confirm position-relative p-4&quot;]/button[@class=&quot;btn btn-primary mt-4 sl-btn d-flex&quot;]</value>
      <webElementGuid>4dfec5bf-3875-419e-a083-f59a6038c289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>ef3c0bdf-e8b2-4c9b-825d-15846fd3654a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-modalDigifHome']/div/div/div/button</value>
      <webElementGuid>3c016a93-ed93-4d0c-a44d-6b8bc957cac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Polis'])[1]/following::button[1]</value>
      <webElementGuid>8bac617d-0666-48ca-bae7-ee8019a25814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::button[1]</value>
      <webElementGuid>f7ab57e8-8a5e-4bf3-af4a-134e7204439c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alberka B Purnama'])[1]/preceding::button[1]</value>
      <webElementGuid>1ecef6ba-6c86-4545-b169-8e7cdefea4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat profil'])[1]/preceding::button[1]</value>
      <webElementGuid>d3636ffc-25b7-428a-989d-1985e0aa1738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buka DIGIF']/parent::*</value>
      <webElementGuid>aecc82ff-9ac9-428f-baca-7df0ef300369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>f2ff4b2e-4f5c-409a-9466-8f3db8239f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Buka DIGIF' or . = 'Buka DIGIF')]</value>
      <webElementGuid>b869c0c1-664f-4c2c-a81f-6078316172ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
