<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link of the session_linkSession</name>
   <tag></tag>
   <elementGuidId>423d0d98-5a86-4a18-934a-3753db20bb97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#linkAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='linkAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dc186ba-0db6-4d54-8587-a11cd9f4c269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fe9119c-5631-49b2-bc3d-0185132f9b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>62d07e3b-b9cb-4043-8ca3-e2029cdae9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>linkAdd</value>
      <webElementGuid>96c701e9-e6c8-4452-b308-c10a30825fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>linkSession</value>
      <webElementGuid>6e54e4fe-2340-498b-b786-af4022af704b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Link Session</value>
      <webElementGuid>471f30fe-2c33-4b62-b25f-dc8e5143900d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b2f04a1a-cceb-43f5-b3ed-5276d6740b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkAdd&quot;)</value>
      <webElementGuid>303fd9a5-70e2-4433-bd02-cda6ba8a08f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='linkAdd']</value>
      <webElementGuid>4299b24a-e711-49f0-8921-753f9cf0c812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[5]/input</value>
      <webElementGuid>73b4e17e-0b40-4aac-81d1-a487aa8e07a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>81297abc-202f-4fff-ad86-fac8bbaa5f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'linkAdd' and @name = 'linkSession' and @placeholder = 'Link Session']</value>
      <webElementGuid>f5f57455-a4f9-4ff8-a275-268338528c31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
