<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Time_startTime</name>
   <tag></tag>
   <elementGuidId>c3407c06-79f2-4c09-b865-d8e4e630fee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#starTimeAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='starTimeAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0785cace-1041-4dbe-90a0-91c5d63ef875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>7dcaec5d-8cda-40c0-a726-1e7082225ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2915a891-665c-4828-be43-c8227be44fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>starTimeAdd</value>
      <webElementGuid>e84dfdb9-e6f7-4368-953a-90b22b810d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startTime</value>
      <webElementGuid>00e40277-6622-4a69-9c25-f15e9b34970d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start Time</value>
      <webElementGuid>e7a13a33-fa3f-4664-a87e-ae7ed8e01806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4009c03e-f48d-4187-acdb-b55bd5f61ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;starTimeAdd&quot;)</value>
      <webElementGuid>9b19ca68-aeee-4590-baa6-c9298294231a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='starTimeAdd']</value>
      <webElementGuid>8327a589-c8ee-4bf1-aec2-f6168369003b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/input</value>
      <webElementGuid>5a0846ae-2881-48ae-aa00-368c2b771ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ba01cd70-cb51-455c-a5a3-7b617787615f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @id = 'starTimeAdd' and @name = 'startTime' and @placeholder = 'Start Time']</value>
      <webElementGuid>efa62b4b-ce8b-4ba0-85aa-3f3cd47c6e42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
