<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Time_endTime</name>
   <tag></tag>
   <elementGuidId>9de05c88-ac1b-43b0-a908-8b9024c4a32d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endTimeAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endTimeAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>198426af-4064-49ac-9a5e-450bb3d48930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>752240f6-2d61-4462-8600-ce6696325641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>24d829d8-82bf-4efc-979b-83384b82c027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endTimeAdd</value>
      <webElementGuid>f540b773-8256-48b9-aef2-3ceaa137a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>endTime</value>
      <webElementGuid>1ebfeef3-94c5-4af0-b1b7-30e3ab78b3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>End Time</value>
      <webElementGuid>0cd57de4-a326-419a-8b6c-411fb5dbb36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>df41e7aa-78ba-46a4-b9d5-e9cf5eb3d37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endTimeAdd&quot;)</value>
      <webElementGuid>aec15ecd-7026-4080-b0e0-b6969ae72bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endTimeAdd']</value>
      <webElementGuid>59d10bfc-b837-4d22-8947-8ca14868f5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/input</value>
      <webElementGuid>f6af4563-7688-4bd9-bd81-190ac7c7f6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>468ff904-736d-4743-8095-e472921c5351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @id = 'endTimeAdd' and @name = 'endTime' and @placeholder = 'End Time']</value>
      <webElementGuid>6ab7314d-63d2-4941-b789-5d811f23b3dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
