<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_32547</name>
   <tag></tag>
   <elementGuidId>40b9326c-fe8d-4219-990b-e954c9b522c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='newAccountId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newAccountId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26e6ffe2-0637-490e-b200-615c47d3e225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newAccountId</value>
      <webElementGuid>76aae88a-ee7a-4455-9af2-24ac4de76507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>activity.htm?id=32547</value>
      <webElementGuid>4293da29-dac9-4c57-a298-1630f03311d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>a12c7c5d-ea22-4a37-aef9-89d2b0d6b964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>32547</value>
      <webElementGuid>ada9fded-03a3-40f2-aea7-9ca0b274f2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newAccountId&quot;)</value>
      <webElementGuid>0cdd7e7d-d84e-4d18-bb56-5865149056c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='newAccountId']</value>
      <webElementGuid>c73ece9d-b809-4a0b-b8a1-1d15589bded0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/p[2]/a</value>
      <webElementGuid>6d5609ee-deb6-43be-8398-434a029a1d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'32547')]</value>
      <webElementGuid>137305be-fc69-41de-94a8-ed1d99ff9003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'activity.htm?id=32547')]</value>
      <webElementGuid>1987c93e-1e1c-47fc-b6fa-6e2474cfc4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>d78320a3-ee28-4fd4-9760-db2424ae0559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'newAccountId' and @href = 'activity.htm?id=32547' and (text() = '32547' or . = '32547')]</value>
      <webElementGuid>1f61611d-9bea-4ac4-80c6-2ae0a692e55f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
