<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Formulir Pengalihan Premi_ms-1</name>
   <tag></tag>
   <elementGuidId>2046ec38-243a-4eb4-bc2d-9c2b0e6babe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/a[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>895e7d1c-f6ec-4cc8-ae12-10d4bd8dcde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/msl/assets/svg/icon-download.svg</value>
      <webElementGuid>2d4dc68d-816b-43f4-8aa3-8e8734a9fd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-1</value>
      <webElementGuid>92e36fea-7a1a-4278-a95c-981206535603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>1451339e-bc3d-48dc-9992-beb7cf401b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>62aaa7b7-cc82-43a3-ae58-34ac3bfba07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;d-flex flex-column align-item justify-content-between h-100&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;container&quot;]/div[3]/div[@class=&quot;table-responsive mt-4&quot;]/table[@class=&quot;table td-p&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;d-flex gap-3 justify-content-between&quot;]/div[@class=&quot;d-flex gap-3&quot;]/a[2]/img[@class=&quot;ms-1&quot;]</value>
      <webElementGuid>7584aa89-a6bd-447c-be27-b0f84dce1d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/a[2]/img</value>
      <webElementGuid>8e7b5171-1ba9-4e0c-ad63-44554a26328c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Download']</value>
      <webElementGuid>14cc0053-bbe3-472f-9afc-e7fe863fc182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>8bc2bdd5-69ed-4b79-a4da-0344c60a61c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/msl/assets/svg/icon-download.svg' and @alt = 'Download']</value>
      <webElementGuid>590ff8ad-9676-4d5c-9bc4-8577254faf13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
