<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginFields</name>
   <tag></tag>
   <elementGuidId>2252fc80-2a8c-4699-bdee-6c2abba4107d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='txt-${FieldName}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='txt-${FieldName}']</value>
      <webElementGuid>90783120-9c7b-4bb8-b20e-ccf80297a77f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
