<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_010215211</name>
   <tag></tag>
   <elementGuidId>8544bfaa-87b8-45af-9983-a2690db8605e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item-0e997084-0b52-4c05-9e74-9368c6ddbc5f']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>21ccad3c-d815-48cb-863e-55101358a0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>92387e1d-38dd-42d6-bcf1-237039aca535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link w-150 </value>
      <webElementGuid>4ca65bf2-0a59-45e4-9ff7-6d8db7657dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>010215211</value>
      <webElementGuid>6af0292e-0d1f-42b4-8e9b-0cb0f2b667bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-0e997084-0b52-4c05-9e74-9368c6ddbc5f&quot;)/a[@class=&quot;nav-link w-150&quot;]</value>
      <webElementGuid>840171b0-f082-4557-8484-a474c7fe7b6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item-0e997084-0b52-4c05-9e74-9368c6ddbc5f']/a</value>
      <webElementGuid>aecc17a7-97ea-4015-ad33-c460e8ce0f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'010215211')]</value>
      <webElementGuid>b29ed960-5607-48cc-b503-62f994685677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C02057684'])[2]/following::a[1]</value>
      <webElementGuid>43aa207e-366c-4f0f-932f-b6b370ac8813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A002268521'])[2]/following::a[2]</value>
      <webElementGuid>5ece80ab-278a-420e-9337-1b2519f0258f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun Medical Executive'])[1]/preceding::a[6]</value>
      <webElementGuid>5e5b30b3-b725-4b0c-92a1-41abc3f74926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '.')])[4]</value>
      <webElementGuid>ce551695-7005-4276-8768-9a1ee75ae1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>8f414cf7-bcf4-4ae5-a7ee-7732b0ab74b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '.' and (text() = '010215211' or . = '010215211')]</value>
      <webElementGuid>abb2f56f-79ee-43e6-89c2-1c78e2cd6a26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
