<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_010080010</name>
   <tag></tag>
   <elementGuidId>8972c9b1-05de-4097-b723-6f881dad16b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item-325e732b-bd46-4361-817e-df798cd4067d']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>590b65e1-dbad-4173-be9d-bb239baa9769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>3680fbd1-344f-4be8-8e55-8abfea96ebdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link w-150 </value>
      <webElementGuid>0f23523a-7486-4583-939b-97af8db234d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>010080010</value>
      <webElementGuid>d5ab0159-2750-454a-a76e-ded643b2054f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-325e732b-bd46-4361-817e-df798cd4067d&quot;)/a[@class=&quot;nav-link w-150&quot;]</value>
      <webElementGuid>0501a44d-2840-4ced-8c77-0a1e41ef2276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item-325e732b-bd46-4361-817e-df798cd4067d']/a</value>
      <webElementGuid>2cbe1037-b8b0-4b2d-80fe-1eafcb4e8dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'010080010')]</value>
      <webElementGuid>2a9e75bd-2d4d-48b0-9196-4ff4d47e5745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C02057684'])[2]/following::a[2]</value>
      <webElementGuid>ef55eaeb-29c0-44ed-932a-9b6ed1b04c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A002268521'])[2]/following::a[3]</value>
      <webElementGuid>fc7e567b-340c-49c0-887d-cc1ac01669bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asuransi Sun Healthcare Solution'])[1]/preceding::a[5]</value>
      <webElementGuid>dab932a2-d793-4a41-8547-a214d0110ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '.')])[5]</value>
      <webElementGuid>4a63fccd-5264-4685-acbd-53c8db99a0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>a8d50186-4fb0-4d6e-8cee-7505cbf7fd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '.' and (text() = '010080010' or . = '010080010')]</value>
      <webElementGuid>decdd18c-99a0-4b4d-8752-ff7a471f3b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
