<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_129207255</name>
   <tag></tag>
   <elementGuidId>e1507a77-d37d-4f53-870a-4b76c4984e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item-3b19c0ae-5d2f-432a-b610-3b9d93ef1e2f']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f1a34d71-76a3-4e68-a659-aa0810dc81eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>ef5aa744-29f4-48b8-97e0-8388f74d02bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link w-150 </value>
      <webElementGuid>42218563-2365-4a4b-9919-cc2ce954791a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>129207255</value>
      <webElementGuid>9eadf0bb-fb02-4939-9abe-a94b1dc62e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-3b19c0ae-5d2f-432a-b610-3b9d93ef1e2f&quot;)/a[@class=&quot;nav-link w-150&quot;]</value>
      <webElementGuid>6928b02f-0c1f-4cd2-9a19-d350f4ea4295</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item-3b19c0ae-5d2f-432a-b610-3b9d93ef1e2f']/a</value>
      <webElementGuid>ca0c2f59-b5d8-45b1-ad09-746e087e9997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'129207255')]</value>
      <webElementGuid>0f7f1429-fdd8-4236-9728-6a3adc786b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C02057684'])[2]/following::a[3]</value>
      <webElementGuid>05fee406-02ca-43ea-8fc9-9a0d504da1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A002268521'])[2]/following::a[4]</value>
      <webElementGuid>42457a0f-5f8b-44c2-af09-5ea64a2ae915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X-TRA PROTEKSI CERMAT'])[1]/preceding::a[4]</value>
      <webElementGuid>64ec7c4d-ae5a-48e5-b898-52c49780d002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '.')])[6]</value>
      <webElementGuid>4507e250-825e-4fc8-9f37-2a2d53e12054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>e15b1f2c-a303-4c08-a95d-889fa7478055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '.' and (text() = '129207255' or . = '129207255')]</value>
      <webElementGuid>4db2bed2-3c6c-44c3-9165-ce08ed2d3662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
