<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_131892851</name>
   <tag></tag>
   <elementGuidId>af13e62b-20d8-48d0-a1b2-944d44a1e4d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item-5a5b6c45-99a8-4d4a-8d06-15d12abd9423']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7864a5d1-b2bd-4253-b41e-d8ca2f59b297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>d96efd29-f9b5-40b5-85d1-b0832dcb4f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link w-150 </value>
      <webElementGuid>482f4dd6-a5c1-47b9-8c65-dfef6c159c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>131892851</value>
      <webElementGuid>420f48a8-0ccf-47f9-82fc-005023e88065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-5a5b6c45-99a8-4d4a-8d06-15d12abd9423&quot;)/a[@class=&quot;nav-link w-150&quot;]</value>
      <webElementGuid>0e962e05-ed90-4164-8f42-a420917c7bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item-5a5b6c45-99a8-4d4a-8d06-15d12abd9423']/a</value>
      <webElementGuid>fb8d6ac4-3b51-43f2-a827-b292c9555bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'131892851')]</value>
      <webElementGuid>7026889b-0bd4-47e7-a4dc-88e3b1d348e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C02057684'])[2]/following::a[4]</value>
      <webElementGuid>0fb3947b-678d-44d3-aff1-7b7c9e3c4346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A002268521'])[2]/following::a[5]</value>
      <webElementGuid>45571d9e-094d-43ac-a873-2ac949037b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASURANSI SUN SOLUSI BIJAK'])[1]/preceding::a[3]</value>
      <webElementGuid>bb45ff3a-d173-4e6e-857a-0e717b81b7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '.')])[7]</value>
      <webElementGuid>17b1111c-0c65-40f2-a789-4d7d87756a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>b8345be1-5d64-486b-b2b6-88c6bb6c5f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '.' and (text() = '131892851' or . = '131892851')]</value>
      <webElementGuid>d9f8ef09-837a-4b8a-873c-90fc35c8b2e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
