<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_A002268521</name>
   <tag></tag>
   <elementGuidId>855c7275-a2f4-4a2f-b2a1-df31f093b9eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item-227ea97d-f33e-4f15-bcec-eb8e041d5203']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c54b228e-9815-4261-8c06-73961160cfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>0228e2fa-06e5-41f3-8554-7c39d2af2d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link w-150 </value>
      <webElementGuid>6930d473-5ee5-4cdb-be60-1fc657b07141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A002268521</value>
      <webElementGuid>cf8092dd-0fac-4942-b84c-dce9c73c3953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-227ea97d-f33e-4f15-bcec-eb8e041d5203&quot;)/a[@class=&quot;nav-link w-150&quot;]</value>
      <webElementGuid>c05c81d9-3f8a-476e-99bc-5b0b33d4245c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item-227ea97d-f33e-4f15-bcec-eb8e041d5203']/a</value>
      <webElementGuid>0f738155-1bba-4a6f-ab88-e4e610dea6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'A002268521')]</value>
      <webElementGuid>9c5ad79f-d94f-4dc2-95ba-ee9fd239419a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A60573511'])[2]/following::a[1]</value>
      <webElementGuid>fe1da6e9-83fc-4828-bd83-9e65e00a6685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Pembayaran'])[2]/following::a[2]</value>
      <webElementGuid>27e22ad1-1b42-4639-a3a2-71af8849247d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C02057684'])[2]/preceding::a[1]</value>
      <webElementGuid>fe48dbbb-d96f-4d5b-b9fd-ab4d47b1ef5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Essentia Medical Care'])[1]/preceding::a[8]</value>
      <webElementGuid>3607f5e7-7b60-452e-a34b-80e1c9e4b31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '.')])[2]</value>
      <webElementGuid>b655fba3-e124-47cb-82be-23346f2455fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>2849386b-ab3e-45bf-b0a8-cf7ef02c2400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '.' and (text() = 'A002268521' or . = 'A002268521')]</value>
      <webElementGuid>d673a5f5-97d9-4c27-8631-168dc958af9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
