<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_C02057684</name>
   <tag></tag>
   <elementGuidId>cb952670-8db6-4aef-9393-09c07aec1888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item-32385710-8a02-4bb9-8697-78ba30dcbb31']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4cd1a7d3-0103-4ddf-8ea6-9e20a6f16e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>43120763-e473-4ea7-ba7f-bd95f640724c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link w-150 </value>
      <webElementGuid>62c14454-bdb6-43d9-b517-f0ccc596e3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C02057684</value>
      <webElementGuid>98a74cd4-a81b-417e-aae4-e60eb923cef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-32385710-8a02-4bb9-8697-78ba30dcbb31&quot;)/a[@class=&quot;nav-link w-150&quot;]</value>
      <webElementGuid>c7cc4ea7-2e8a-4741-a80e-79ebf616d2ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item-32385710-8a02-4bb9-8697-78ba30dcbb31']/a</value>
      <webElementGuid>621ad693-1613-49a6-81ac-459f3cae9b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'C02057684')]</value>
      <webElementGuid>81bc5dc5-687d-4fcf-bd72-ef4d9be9fc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A002268521'])[2]/following::a[1]</value>
      <webElementGuid>2a6403a0-5aee-4e6d-a0ca-2fe17d92c7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A60573511'])[2]/following::a[2]</value>
      <webElementGuid>3eb79091-f011-4f6c-993d-73b617a94a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Essentia Medical Care'])[1]/preceding::a[7]</value>
      <webElementGuid>735110cf-8045-44c1-873e-077115e093e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '.')])[3]</value>
      <webElementGuid>0e0f2872-2587-4ddd-bd98-81aff8f4d739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>596ad4ba-07a4-4441-9a79-448036d87c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '.' and (text() = 'C02057684' or . = 'C02057684')]</value>
      <webElementGuid>beb0da6c-5224-4324-aedf-9067695670fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
