<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_6 Bulan Terakhir12 Bulan Terakhir24 _d7c5df</name>
   <tag></tag>
   <elementGuidId>ad7db9d5-32f2-4d59-97ac-d91149c01559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>491a6622-416a-4643-b69d-a47ac051b3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>463bbf3f-8c2d-40c7-9fc4-9ae38ee25b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select </value>
      <webElementGuid>556b7b65-483c-42e6-b9f4-017c96032913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Periode:</value>
      <webElementGuid>7b9d0480-720e-43a7-8586-6c30b34fbb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Periode:</value>
      <webElementGuid>0332229e-d414-4d2e-8845-ffbd26b8c5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6 Bulan Terakhir12 Bulan Terakhir24 Bulan Terakhir</value>
      <webElementGuid>e999296e-94f6-4198-b735-547a0b2ad353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;d-flex flex-column align-item justify-content-between h-100&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;offset-md-8 col-md-4 offset-lg-9 col-lg-3&quot;]/div[@class=&quot;sl-dropdown my-3&quot;]/div[@class=&quot;d-flex align-items-center gap-3&quot;]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>d23cc95e-374b-4670-a37b-d710c8310ad3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@type='text'])[2]</value>
      <webElementGuid>67d01191-63d3-4499-bff1-e86270debf1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[5]/div/div/div/select</value>
      <webElementGuid>6ad03c10-a46e-4bdc-b661-a6ae932cc820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode:'])[1]/following::select[1]</value>
      <webElementGuid>cd78fafd-ada2-4379-9611-c5c4b6072f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Transaksi'])[1]/preceding::select[1]</value>
      <webElementGuid>a5aba3a8-a8bd-4c2e-8102-48db4f6e7971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Bayar'])[1]/preceding::select[1]</value>
      <webElementGuid>df7eaea1-633d-45b9-96e3-d85030826026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/select</value>
      <webElementGuid>81e2a6b4-c1ab-44a5-9a9b-b5611aeda0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and (text() = '6 Bulan Terakhir12 Bulan Terakhir24 Bulan Terakhir' or . = '6 Bulan Terakhir12 Bulan Terakhir24 Bulan Terakhir')]</value>
      <webElementGuid>3be106bf-23b7-4378-ae97-92a79a9949a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
