<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_payee.phoneNumber</name>
   <tag></tag>
   <elementGuidId>30607220-5ffe-45f4-bd02-94aeb8542391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='51df2ede-793a-4240-8822-c11f0d4f1d6b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#51df2ede-793a-4240-8822-c11f0d4f1d6b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdab7ea0-f444-48de-991a-fbb543d67523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>51df2ede-793a-4240-8822-c11f0d4f1d6b</value>
      <webElementGuid>c6d09585-6a60-4e30-bf7d-dcda7adbc31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input phone-number-51df2ede-793a-4240-8822-c11f0d4f1d6b ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>ce5048b7-9543-432a-ac57-84ebd9a05f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payee.phoneNumber</value>
      <webElementGuid>0bb176f8-b8cf-4d1d-9d49-58b81dde9eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.phoneNumber</value>
      <webElementGuid>6a844e0c-7886-48ba-946d-76821a971589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;51df2ede-793a-4240-8822-c11f0d4f1d6b&quot;)</value>
      <webElementGuid>e771b7d7-9109-41b0-9cf1-c53b872cf20e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='51df2ede-793a-4240-8822-c11f0d4f1d6b']</value>
      <webElementGuid>4ea2dc69-a519-42d8-92e3-e22cceac3998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>b1796252-e3ce-4473-b998-2d7c286ce79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>1e7e22d6-2b13-4be7-94ce-34ab6ac8d8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '51df2ede-793a-4240-8822-c11f0d4f1d6b' and @name = 'payee.phoneNumber']</value>
      <webElementGuid>2cb64cb3-62b4-4aec-a6d5-0cc67887f4b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
