<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_payee.address.state</name>
   <tag></tag>
   <elementGuidId>da5ac5fb-55eb-4d75-ae73-30c769649343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='payee.address.state']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;payee.address.state&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7c35a90-e2e0-4afa-bbc3-ad4d967c1012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>c462a0b7-768f-4588-af47-512c33ae465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payee.address.state</value>
      <webElementGuid>8b6e12d5-df6b-44a5-b0b3-8d1cbc201b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.address.state</value>
      <webElementGuid>a32a98b5-8e03-448b-9e2b-56b5890e4b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[1]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/table[@class=&quot;form2&quot;]/tbody[1]/tr[4]/td[2]/input[@class=&quot;input ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>0e86af09-3e58-47d1-91ea-0fc3e4371df8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='payee.address.state']</value>
      <webElementGuid>52d79d4e-1153-4149-a5fd-73f9cf3bf408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>445f6570-274f-4877-9c07-442cc33daa6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>c0d46300-e3ca-4a1f-972d-6c43ee872363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payee.address.state']</value>
      <webElementGuid>a46f0f77-6e3d-462c-9d3f-184a88509580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
