<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_payee.name</name>
   <tag></tag>
   <elementGuidId>0d3ec841-c6e6-4de0-8a5f-7978a5a6025f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='payee.name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;payee.name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d2d1059-c41d-4948-933c-c28a8ccb178e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payee.name</value>
      <webElementGuid>25e4a650-1de0-48c7-a301-f60e7b7e4960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>e1624835-12c0-4b9b-8d02-90e4ec4d7aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.name</value>
      <webElementGuid>ad132c9d-b4aa-4c65-afe2-595a38f61de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[1]/form[@class=&quot;ng-pristine ng-valid&quot;]/table[@class=&quot;form2&quot;]/tbody[1]/tr[1]/td[2]/input[@class=&quot;input ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>ca4ec8b9-7774-46d6-8972-c65a8238f98e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='payee.name']</value>
      <webElementGuid>52fcba4a-a48b-4997-b070-aa93ae69a2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr/td[2]/input</value>
      <webElementGuid>29c22e5a-520e-4207-9aa9-8054cd6f81fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>50e28783-aa07-4e7f-adda-d2e051c98b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payee.name']</value>
      <webElementGuid>9e1f350b-50fe-494d-accd-ccf4d4f6432d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
