<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Penjualan Melalui Bank dan lainnya</name>
   <tag></tag>
   <elementGuidId>eda8af74-e6f3-4340-ab51-ee2837b8814b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de6b5466-cff3-467e-9ec9-4b5937e46fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>e9102e67-750d-486d-84cf-539129bc39fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>573d8c60-ba76-4b88-b5ca-243622dc264d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penjualan Melalui Bank dan lainnya</value>
      <webElementGuid>d926fa7a-6abe-4693-a109-c909cc6b5479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;d-flex flex-column align-item justify-content-between h-100&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;sl-tabs mt-5&quot;]/div[@class=&quot;stack-tab-container&quot;]/div[@class=&quot;nav-tabs scrollable-tabs&quot;]/div[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>6af3c3e7-4d0c-4cc5-9fac-d0b7c328d291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div/div/div[2]/a</value>
      <webElementGuid>97c619de-36d0-4751-a948-e2723318ec59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Penjualan Melalui Bank dan lainnya')]</value>
      <webElementGuid>8276fed7-9211-419a-ac00-efab2c8f105f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjualan Melalui Agensi'])[1]/following::a[1]</value>
      <webElementGuid>461adc8f-0c52-4032-8b55-8512508a233a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pembayaran'])[2]/following::a[2]</value>
      <webElementGuid>b6876775-01f7-4f74-9abe-44678f97f40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran Premi/Kontribusi Pertama'])[1]/preceding::a[1]</value>
      <webElementGuid>b14c603c-1c83-4a38-bc17-69829ba55ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asd'])[1]/preceding::a[1]</value>
      <webElementGuid>1923f044-cbe4-43c1-b3ce-382b29407bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penjualan Melalui Bank dan lainnya']/parent::*</value>
      <webElementGuid>eb378159-078a-4b72-981a-ed559cf42df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '.')])[2]</value>
      <webElementGuid>5144d450-3b7f-4a0c-9dda-a84ffe6e6746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>834aaa2b-4243-4ce0-9915-9df12eaf265d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '.' and (text() = 'Penjualan Melalui Bank dan lainnya' or . = 'Penjualan Melalui Bank dan lainnya')]</value>
      <webElementGuid>4e541bfd-bafb-4f81-adae-938156ea66b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
