<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pembayaran PremiKontribusi Pertama</name>
   <tag></tag>
   <elementGuidId>345c9c4a-52c8-460a-8d12-7acb341d4f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.accordion-button.p-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77fc74ef-090b-4fe2-8b8b-89f105690d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button p-4</value>
      <webElementGuid>e87afefd-d333-47fa-98b8-ef6cbdd40922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a148fd9-a9ac-4f66-9563-79d462be755a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>7b03cdd6-c0d0-4d5b-9b0b-f55e1ed98428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#pembayaranViaAgent-1765f280-63b0-4815-b5a5-a6e2647f128d</value>
      <webElementGuid>a74bdbd9-5180-42d7-a988-dfa7ded8004b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f10966e7-bba0-4118-a3f1-ec4bc652489b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pembayaranViaAgent-1765f280-63b0-4815-b5a5-a6e2647f128d</value>
      <webElementGuid>4585e238-178a-4f1c-8d17-23b6c5667299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pembayaran Premi/Kontribusi Pertama</value>
      <webElementGuid>116521e5-bff1-44f8-8a1c-8e7ceed9a35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panelsStayOpen-pembayaranViaAgent-1765f280-63b0-4815-b5a5-a6e2647f128d&quot;)/button[@class=&quot;accordion-button p-4&quot;]</value>
      <webElementGuid>5fff8d06-26d5-4460-85e1-2b408e2ee610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>1bb0c71e-a411-4743-8e1f-b7daf3fc6e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='panelsStayOpen-pembayaranViaAgent-1765f280-63b0-4815-b5a5-a6e2647f128d']/button</value>
      <webElementGuid>bada5ce9-3395-4dfa-9919-e3336cca52bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjualan Melalui Bank dan lainnya'])[1]/following::button[1]</value>
      <webElementGuid>917c3972-3f97-4198-a56e-ed1523780ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjualan Melalui Agensi'])[1]/following::button[1]</value>
      <webElementGuid>20e81c4f-8b3b-4315-9dc1-c1247f04db8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asd'])[1]/preceding::button[1]</value>
      <webElementGuid>51430a1f-ce3f-4af0-b447-c58c6b949730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/button</value>
      <webElementGuid>741afc5f-7c76-4699-9874-f5b6a2c530b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Pembayaran Premi/Kontribusi Pertama' or . = 'Pembayaran Premi/Kontribusi Pertama')]</value>
      <webElementGuid>a8e5a4c5-8ef5-455a-acfa-f16f5e35edde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
