<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A_correctAnswer</name>
   <tag></tag>
   <elementGuidId>fdc0d5c6-11b6-4e73-b6e1-f310bb0b4b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#correctAnswerAddA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='correctAnswerAddA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f229917b-6776-4edb-810d-e096bf3c7abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4cca0415-63a5-4c0a-b79e-d04b61af2796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>correctAnswer</value>
      <webElementGuid>a7327d72-28ac-4da9-9d73-a159c4ab1489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>correctAnswerAddA</value>
      <webElementGuid>c43227da-225e-4d17-8c5c-44c637a9e64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f1857f0-147c-4b63-91b8-32467fa4d1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;correctAnswerAddA&quot;)</value>
      <webElementGuid>a60550d3-7ad4-4bb1-90fd-77ed3e8af54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='correctAnswerAddA']</value>
      <webElementGuid>e4fe0dd1-76f5-4acc-96e1-f9718d95b616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[5]/div/label/input</value>
      <webElementGuid>6c116241-7eec-4026-9e50-1a62a03af828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label/input</value>
      <webElementGuid>8220265c-0a04-4848-a0a8-39a997657cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'correctAnswer' and @id = 'correctAnswerAddA']</value>
      <webElementGuid>8055e987-229b-4e05-b962-9c754daaefca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
