<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please choose one_isActive</name>
   <tag></tag>
   <elementGuidId>e1c7888f-9d14-40db-8ddf-af1190a6b327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isActiveAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isActiveAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ec16bc0-cad6-4bfd-a771-04eb41402fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e50977bd-599a-4aff-8ab0-cd0996280f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>205dfc1a-823d-413c-bdd4-e678862d44bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isActive</value>
      <webElementGuid>ecddb041-e235-4581-8a91-c8ee4c32f66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isActiveAdd</value>
      <webElementGuid>19bb0362-32ad-446d-8aa0-0131c9db4046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isActiveAdd&quot;)</value>
      <webElementGuid>bf381d46-29a6-487f-9330-6dfe56337a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isActiveAdd']</value>
      <webElementGuid>bddcce0b-c28e-4001-883a-f85e35ddcc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[6]/input</value>
      <webElementGuid>687aee77-e8ed-46bf-81e3-f4c179b232bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>479e2570-c525-434f-8767-1bb6e55a73dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'isActive' and @id = 'isActiveAdd']</value>
      <webElementGuid>1f50d6ac-09b7-4d81-bfbc-f8855e04b7ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
