<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_No results found</name>
   <tag></tag>
   <elementGuidId>88b5b7ff-ac7f-4de0-adca-328748d9893a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.select2-results__option.select2-results__message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-chapterAdd-results']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6e9d34f7-2bdf-4710-873d-9c07b78b5e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>19508df0-21b3-41d4-95a9-b531a57b919a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>89c931c6-e8d9-4994-a3e2-7a657fb45db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__message</value>
      <webElementGuid>e91c81ac-0d6e-4af8-9fcd-87ed3b76daa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No results found</value>
      <webElementGuid>e5e363f3-5572-4288-8c4c-ae8f8378e27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-chapterAdd-results&quot;)/li[@class=&quot;select2-results__option select2-results__message&quot;]</value>
      <webElementGuid>7e373d7b-6b2b-4955-8126-4107ed91f09c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-chapterAdd-results']/li</value>
      <webElementGuid>d98fe829-16d7-4cd4-a31a-30ae65ebcc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::li[1]</value>
      <webElementGuid>730ab6a1-3529-4639-b5c8-992f43e70eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::li[1]</value>
      <webElementGuid>6befd242-64ee-4cf3-b84d-a7e6c9c373d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level *'])[2]/preceding::li[1]</value>
      <webElementGuid>dea82d8d-230a-4a60-a51d-f2cf7d6abb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module *'])[2]/preceding::li[1]</value>
      <webElementGuid>6d37d3f8-4543-40ae-b3af-a4d59e24dbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No results found']/parent::*</value>
      <webElementGuid>45588027-f6b0-4556-86e1-9c07bacd7975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li</value>
      <webElementGuid>32c45607-02fa-4d98-bbce-ea30f61e40fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'No results found' or . = 'No results found')]</value>
      <webElementGuid>523fab41-1dc5-4b61-a7da-fcb816c82f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
