<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Choose Chapter --_1</name>
   <tag></tag>
   <elementGuidId>477ab97b-efa6-4cb3-9fb7-2874f9d52c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-chapterAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-chapterAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0edca20a-b7ab-4de3-a18f-0e54f3ff8f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>aa6a04d6-8a12-4da6-8fdd-84c77ae8bef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-chapterAdd-container</value>
      <webElementGuid>b7f58326-891c-4534-95ef-d117483a6562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Chapter 1</value>
      <webElementGuid>56be39ba-92ff-44f4-b996-58ac6f602fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Chapter --</value>
      <webElementGuid>79e6dd14-f48b-405d-8707-1c993ee8daea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-chapterAdd-container&quot;)</value>
      <webElementGuid>c3b4f1e6-e604-431e-b8fb-abfa8a9ebce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-chapterAdd-container']</value>
      <webElementGuid>ab6c8ad6-e0fa-4c3b-abf8-944191ef712c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>f6b0b9e5-0312-46fb-8763-0d07c8948757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chapter *'])[1]/following::span[4]</value>
      <webElementGuid>65c544eb-771b-44cb-bf7f-f9896b62fe0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::span[6]</value>
      <webElementGuid>1ed49d89-7d34-4830-a210-b618f1848e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question *'])[1]/preceding::span[4]</value>
      <webElementGuid>796c1c24-71bc-4441-ba0e-dd77f5a09621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span/span/span</value>
      <webElementGuid>c91c81de-de30-41ec-83f0-2940277c302e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-chapterAdd-container' and @title = 'Chapter 1' and (text() = '-- Choose Chapter --' or . = '-- Choose Chapter --')]</value>
      <webElementGuid>8c589595-95d9-47d3-a27a-a956d3cd3363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
