<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Level 1</name>
   <tag></tag>
   <elementGuidId>cba1f892-cc61-4fc7-8cdb-6ee65422c4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-levelAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-levelAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>60a25da6-336e-4dc5-8d9e-697668409dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9f1ad0de-491f-4e6c-99b7-f9b3e13ba36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-levelAdd-container</value>
      <webElementGuid>5b4e10f6-3c42-4abd-b719-27b23c846568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Level 1</value>
      <webElementGuid>66106bbe-5fcd-4fba-8349-547f99d3fe96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Level 1</value>
      <webElementGuid>a365e229-aa70-4936-8bcc-94fad3fdcd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-levelAdd-container&quot;)</value>
      <webElementGuid>dcd6900a-23c9-4e28-ab42-551a54e617fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-levelAdd-container']</value>
      <webElementGuid>80987ae7-7beb-4c06-bc22-41c0d5f1bf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/div/div/span/span/span/span</value>
      <webElementGuid>499cf345-b43a-40d2-b0ff-5cc509356963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level *'])[1]/following::span[4]</value>
      <webElementGuid>bd3cc637-af6b-4e1a-af3e-0155fde95e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Question'])[2]/following::span[4]</value>
      <webElementGuid>1c40b28f-4ca4-4df9-8f7c-618ccf154a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module *'])[1]/preceding::span[4]</value>
      <webElementGuid>d2ba7c6a-face-4d4e-b019-08a2019006f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>d1b1f973-25d2-4293-98f8-edf178a06a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-levelAdd-container' and @title = 'Level 1' and (text() = '×Level 1' or . = '×Level 1')]</value>
      <webElementGuid>cdcecd2a-6b66-46c1-bf92-bbdc829c9dd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
