<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Option A_optA</name>
   <tag></tag>
   <elementGuidId>2f1e450e-ff80-42fe-8fa9-152e7545da1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optAAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optAAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c0002c2c-26e7-4cbe-b658-775fbcc1fe73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e82b0c64-61d4-4789-850f-edb6079d4bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optA</value>
      <webElementGuid>f461935b-913b-4e25-87de-3f80977eb3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optAAdd</value>
      <webElementGuid>32cde988-9103-4f85-8b09-cb97d9c0053c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d631691d-5f27-4cca-b68e-fc024166c555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option A</value>
      <webElementGuid>a99db21c-f361-4d43-a820-08ce39d3bf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>1643e69c-e171-42ba-a636-e538b57b4113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optAAdd&quot;)</value>
      <webElementGuid>a505132c-af17-4445-9fbc-2ef3003e15f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optAAdd']</value>
      <webElementGuid>46441cbf-9ca8-472d-af0b-0e8bdf05777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/div/div/textarea</value>
      <webElementGuid>6852cb53-56e3-425d-83d6-1f1e1b3017ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/textarea</value>
      <webElementGuid>96ac4767-eb92-4d1b-95c5-26289048d254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optA' and @id = 'optAAdd' and @placeholder = 'Option A']</value>
      <webElementGuid>bc525f87-6991-4a1d-a953-e66d1aea94a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
