<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Question_desc</name>
   <tag></tag>
   <elementGuidId>21a68a76-d8cb-48b7-aaf5-9e14cc49bf11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='descAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>02868e19-9d81-43f0-a14d-d67fc1abc652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>22848f7f-12cb-416e-815b-a9750ca68956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>desc</value>
      <webElementGuid>b4853d5d-b09e-484d-8dd1-98b52b5b7de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descAdd</value>
      <webElementGuid>3c52bdec-b1b8-4776-9198-795c84f1d7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>341bdfd0-d5e4-486f-93ed-ddfe9ecf12a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>ec14a878-5831-4462-8829-a8800c6d38ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Question</value>
      <webElementGuid>ebf83e72-a248-46d0-a0f6-66d331739bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descAdd&quot;)</value>
      <webElementGuid>22b1b12b-a8ba-4a02-8581-6eec18b903bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='descAdd']</value>
      <webElementGuid>4e5a2e67-b962-4145-bfeb-9e57097209df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/div[2]/div/textarea</value>
      <webElementGuid>6046925c-6696-4df1-b884-ee51a734c5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9249cfbe-a1cd-4cde-aea4-15fe216f9f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'desc' and @id = 'descAdd' and @placeholder = 'Question']</value>
      <webElementGuid>1529271f-133a-43ec-aa48-5643447f7172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
