<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Option C_optC</name>
   <tag></tag>
   <elementGuidId>f8fe2f00-dbc8-4956-af3e-af80e55ee35a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optCAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optCAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7652c410-9c1c-4c27-a67f-617ed2c76e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eaf5a9d8-a455-4c62-ba64-1c9fbfd1ce8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optC</value>
      <webElementGuid>d4f0b1ad-f655-4312-95b4-409934d3f202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optCAdd</value>
      <webElementGuid>9fd91407-6177-4ddc-8b6d-d5bdecd5e969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>086f5b7f-d163-4151-a7ab-f4bf3c5541a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option C</value>
      <webElementGuid>3b18d8d1-10ea-461b-b771-08ec765f388e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>51dc9062-96f3-4f93-b851-855f10c6e2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optCAdd&quot;)</value>
      <webElementGuid>69eaf39c-f0bf-463c-8e83-b6014dca290e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optCAdd']</value>
      <webElementGuid>1daac108-f08e-439b-b37a-b4a1e6e7c8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/div/div/textarea</value>
      <webElementGuid>12236554-14f8-4896-b8ab-c18a76101680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>4b342470-eb04-4750-b549-ac7b34a0ecc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optC' and @id = 'optCAdd' and @placeholder = 'Option C']</value>
      <webElementGuid>001a5d3d-6bb2-4686-a362-410a23f6eecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
