<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Option D_optD</name>
   <tag></tag>
   <elementGuidId>d8174d60-c4b7-4269-8a1d-e09cd2fd41ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optDAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optDAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0bface75-6791-49d1-ac7c-64dcb15fbd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f860f06a-7fcc-4f04-8959-9563cc62aeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optD</value>
      <webElementGuid>ecd5a809-a35b-49a7-a4c0-80d2d25e53a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optDAdd</value>
      <webElementGuid>26d1ee3a-f5ab-4b5b-9fdc-605a419aa780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>52af58bc-dfe5-4b5f-aee1-941ce49cd784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option D</value>
      <webElementGuid>763700de-aea2-4f1a-87f3-f64b61180697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>358c52d8-39c5-4cbb-9c16-5f284ac65a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optDAdd&quot;)</value>
      <webElementGuid>34739e4c-bc71-429c-bf80-92425624a304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optDAdd']</value>
      <webElementGuid>ca70d548-7816-4db9-b767-eeb00424ca14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/div[2]/div/textarea</value>
      <webElementGuid>31578be4-3f12-4e65-a92a-85353fb7befa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/textarea</value>
      <webElementGuid>831c67d0-c0ef-433e-8ecb-7521a4e9f6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optD' and @id = 'optDAdd' and @placeholder = 'Option D']</value>
      <webElementGuid>84900032-bba9-4270-a4fa-40e48a9692ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
