<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Option B_optB</name>
   <tag></tag>
   <elementGuidId>f15067c2-0403-461c-bbb1-d045c8736e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optBAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optBAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1d94466d-4064-4e52-881d-e4a61891648b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e4a0bec9-e2cd-4d00-9dc8-db21e1771fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optB</value>
      <webElementGuid>9b759223-ba95-4c77-9e7a-95b325b5a657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optBAdd</value>
      <webElementGuid>a9c76e13-cfd6-4495-b420-36f7f4b9f50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1b0cd61f-373b-42df-a193-d46b5cb4ce8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option B</value>
      <webElementGuid>ae6cd52c-8b15-41b3-949b-66f188357c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>08cf38be-dd86-4f12-8cda-f04e997741fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optBAdd&quot;)</value>
      <webElementGuid>bcdc591f-fd66-4c49-8bbe-1aade41a395e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optBAdd']</value>
      <webElementGuid>81da5901-4c20-4c3a-a447-a9930981820a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/div[2]/div/textarea</value>
      <webElementGuid>caff4b37-6cf0-4f8d-b43e-56000a0c2fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/textarea</value>
      <webElementGuid>9af58a1a-8a3b-4aa5-a60e-21a990123828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optB' and @id = 'optBAdd' and @placeholder = 'Option B']</value>
      <webElementGuid>8adb7977-45fe-40f4-9e3d-9d2a53d004a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
