<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_isActive</name>
   <tag></tag>
   <elementGuidId>870fd0dc-ac3f-4b43-add2-405825e7a084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isActiveAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isActiveAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8e5e0a4-2841-41f4-9c78-4adfda5eac67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f6a1f3dc-cc96-425e-8f95-cae60f63a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>844e450a-7407-4d50-8ed0-035b18b59901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isActive</value>
      <webElementGuid>a87d541c-e569-4695-83fb-23d5f5ff464b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isActiveAdd</value>
      <webElementGuid>892630ef-0d06-4dc9-b4ee-4dfae65271ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isActiveAdd&quot;)</value>
      <webElementGuid>5e2e3c16-8188-4403-903d-f50db86c3b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isActiveAdd']</value>
      <webElementGuid>73642958-8c41-47ab-82a9-8b401177cd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/input</value>
      <webElementGuid>ea66369d-fb41-4135-a6e8-947de73889f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/form/div[2]/div[4]/input</value>
      <webElementGuid>b4c2eb9c-98df-4a5c-b3e6-322b7539d2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'isActive' and @id = 'isActiveAdd']</value>
      <webElementGuid>1f5961d5-3bb7-477a-ae13-9cbb8d365ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
