<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tahunan_periode</name>
   <tag></tag>
   <elementGuidId>8267e586-7f4a-41c0-894e-0f672bf989e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Bulanan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Bulanan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63530820-dcf0-4579-9e8e-09acca87cdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>1bc2ffc5-b719-47a2-be12-9a7ed50125c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b2abb87a-f0fd-46c6-b868-a7cd037c216b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>periode</value>
      <webElementGuid>d4f5eb3b-9bfb-43f6-b970-057a711306d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Bulanan</value>
      <webElementGuid>467a01e0-25e6-4f4b-b11f-de0cfc7be654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Bulanan&quot;)</value>
      <webElementGuid>933177a5-c20d-4db5-848b-8402b0959a06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Bulanan']</value>
      <webElementGuid>6538dcfd-1418-40bc-a0bf-ae7b6c169295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-modalDownload']/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>ea7f5bf3-62dc-4d36-b5f7-4924c30e9677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9507e5dd-5c74-41ae-b89e-a4a660f747f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'periode' and @id = 'Bulanan']</value>
      <webElementGuid>dc12f50d-0c7e-4ca7-bbf6-b393cd800cc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
