<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode_periode</name>
   <tag></tag>
   <elementGuidId>1b356e9e-08fe-4a00-91e2-2940fa9ac7df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Tahunan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Tahunan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dbd9bdc-621d-45d6-a047-a205feee3477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>a28ab22c-5c4f-424b-acf4-e43e0d877a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>72e39c3f-d505-48d8-a1ac-3981a3119203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>periode</value>
      <webElementGuid>f9be1d28-da71-4e17-99c5-5e1bb677706e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Tahunan</value>
      <webElementGuid>a3f38704-461f-482b-9a98-78e565f51281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tahunan&quot;)</value>
      <webElementGuid>aaed8fee-2f7d-47ba-a54a-85312fec0954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Tahunan']</value>
      <webElementGuid>371db357-15a6-49b3-9f04-6e288842df46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-modalDownload']/div/div/div/div/div/div/div/input</value>
      <webElementGuid>30114b79-556b-4456-a1c4-fdfd2dfe4561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b410dc59-13a4-4a22-a49f-722dd6afa86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'periode' and @id = 'Tahunan']</value>
      <webElementGuid>9026dc5a-546c-4c02-b2da-5f6b45560da0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
