<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tahun20232022202120202019201820172016</name>
   <tag></tag>
   <elementGuidId>2fbb70a7-6ad2-4ac7-ba76-e1e73eddf81a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='tahun']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;tahun&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>834cfa5b-4e9d-462a-a25d-9c23f95e688d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8084bf89-8549-4c55-a8f4-b06315b357d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select text-muted </value>
      <webElementGuid>dbeb0dee-cd51-4791-bf9e-f1cf4ee82d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tahun</value>
      <webElementGuid>42486518-51bd-4381-866c-86da1b857892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Tahun</value>
      <webElementGuid>4c9eef13-7ec8-4a2c-a696-94e0be3486f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tahun</value>
      <webElementGuid>42682347-82a3-4dd1-bd78-4c960f62ce33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tahun20232022202120202019201820172016</value>
      <webElementGuid>3df1135e-c128-4606-8c67-8b67c61096c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-modalDownload&quot;)/div[@class=&quot;modal-dialog position-relative modal-lg&quot;]/div[@class=&quot;modal-content rounded-0&quot;]/div[@class=&quot;modal-body modal-confirm position-relative p-4 d-flex flex-column gap-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;sl-dropdown my-3 form-floating&quot;]/select[@class=&quot;form-select text-muted&quot;]</value>
      <webElementGuid>30a626b9-a8ca-4fe0-a0fa-83ceaa4449c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='tahun']</value>
      <webElementGuid>701c0c20-3caa-49e4-a9cc-5b6bd0f8fb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-modalDownload']/div/div/div/div/div/div[2]/select</value>
      <webElementGuid>f88adf6b-c24c-4664-928c-fd3bcece6a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulanan'])[1]/following::select[1]</value>
      <webElementGuid>306ab81b-e411-4f3c-a401-35f8b6412be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahunan'])[1]/following::select[1]</value>
      <webElementGuid>b0e2308c-1403-4444-b479-1d1ea6955572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[2]/preceding::select[1]</value>
      <webElementGuid>57dc6235-a3c2-410e-b328-0f67f08d70ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulan'])[2]/preceding::select[2]</value>
      <webElementGuid>918ea40d-fe06-4df0-91f2-ee281e9a5bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>bc87b9fc-ba6a-4ec5-858a-58c06ce44b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @name = 'tahun' and (text() = 'Tahun20232022202120202019201820172016' or . = 'Tahun20232022202120202019201820172016')]</value>
      <webElementGuid>787fe3c2-a05c-46a2-b493-28116344aa78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
