<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BulanJanuariFebruariMaretAprilMeiJun_f02c42</name>
   <tag></tag>
   <elementGuidId>3eea32f7-885c-4bae-9e7a-b7202529db2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='bulan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;bulan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf5c1aad-2daf-4585-8a7a-1effcd71ada2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f10c901a-56d0-473e-9b66-257ea061d45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select text-muted </value>
      <webElementGuid>53544097-b6cc-42d8-a33c-b59eb178991b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Bulan</value>
      <webElementGuid>0b2fd205-be59-4af3-81a0-02ae46691041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Bulan</value>
      <webElementGuid>c9aa7d9c-d55f-4e4c-810e-2f621c9b39c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bulan</value>
      <webElementGuid>b67c91dc-e9b1-4421-a607-d9ae81243003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BulanJanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovember</value>
      <webElementGuid>cba30575-603d-4331-8e8a-f9ccfcd80005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-modalDownload&quot;)/div[@class=&quot;modal-dialog position-relative modal-lg&quot;]/div[@class=&quot;modal-content rounded-0&quot;]/div[@class=&quot;modal-body modal-confirm position-relative p-4 d-flex flex-column gap-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;sl-dropdown my-3 form-floating&quot;]/select[@class=&quot;form-select text-muted&quot;]</value>
      <webElementGuid>b51b1d00-4d67-494c-9f2c-6e1a84bbe7ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='bulan']</value>
      <webElementGuid>1f1ebcd5-9369-414d-95d0-0bc796251665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-modalDownload']/div/div/div/div/div/div[3]/select</value>
      <webElementGuid>871f6928-59eb-45b5-9441-a1fb7e7d6075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[2]/following::select[1]</value>
      <webElementGuid>2bd9927b-f66c-4518-99ce-d5d706bab1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulanan'])[1]/following::select[2]</value>
      <webElementGuid>9becece4-f303-4436-8d9c-cee155093814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulan'])[2]/preceding::select[1]</value>
      <webElementGuid>c6129a34-1f99-4ef1-bab9-ed30c1031b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::select[1]</value>
      <webElementGuid>20dc2f85-ed07-435a-8b37-16f899a3e3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>7c4d92a1-a857-429e-b665-8ac43c329948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @name = 'bulan' and (text() = 'BulanJanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovember' or . = 'BulanJanuariFebruariMaretAprilMeiJuniJuliAgustusSeptemberOktoberNovember')]</value>
      <webElementGuid>b4dd988e-57f8-4bf9-83e4-7e569e525dcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
