<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>263c3104-6772-4175-a656-b67b246bb3e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99ec0525-c4a1-4482-947c-0fa13baababc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e1d8ddd4-6a2e-4471-8dd6-b14dc0fcfa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-pill</value>
      <webElementGuid>4794e9a4-35b8-4b9d-954b-0f1e25a9d70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSave</value>
      <webElementGuid>17d846cf-ce3d-41d3-b1f8-925dc5a3aa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>09b4e62a-9f70-4d6f-b9fa-c79c6aa7564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSave&quot;)</value>
      <webElementGuid>794c4343-66e2-4de9-ae1d-80ce3b33c5f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSave']</value>
      <webElementGuid>6b8696de-1fa9-4670-bafc-662f4fb9573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[3]/button[2]</value>
      <webElementGuid>d037fb6b-3025-47d6-b365-e629e60c1de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[10]/following::button[1]</value>
      <webElementGuid>bd7ec941-66bb-4d4a-979a-13b35a4bc229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name *'])[8]/preceding::button[1]</value>
      <webElementGuid>9671318b-8498-44dc-820f-f049adbc1c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Instansi *'])[2]/preceding::button[1]</value>
      <webElementGuid>ccb6551b-8acd-407c-b30a-1378f14709c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>d8066420-e3f0-4e5c-a032-3430aae0d989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/form/div[3]/button[2]</value>
      <webElementGuid>12f4f391-6505-4fc4-8836-34693e4e885e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnSave' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>95f571f2-64db-482d-90a4-f8ab680e898e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
