<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Akun Demo - demo_isActive</name>
   <tag></tag>
   <elementGuidId>61180834-93c0-4430-8305-acd4bb9e5171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formAdd > div.modal-body > div.form-check > #isActiveAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='isActiveAdd'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad491cdf-f5f5-42c9-b1c7-f0716b3b064d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a19953bd-7df0-420a-b69f-90b668119455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>18a556d0-a969-4780-a436-fa5728cafd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isActive</value>
      <webElementGuid>a2792ab9-5f59-438a-8fa3-2ca43b28f429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isActiveAdd</value>
      <webElementGuid>556fad2c-5a99-4030-943b-70ddd8ad3569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAdd&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-check&quot;]/input[@id=&quot;isActiveAdd&quot;]</value>
      <webElementGuid>02f3128f-ecf2-452b-8ff2-6dcdb8924888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='isActiveAdd'])[2]</value>
      <webElementGuid>b9037675-54d3-4183-9e1e-07232f7c5b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/input</value>
      <webElementGuid>656abfdd-9bb3-4845-8000-30515fcad9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/form/div[2]/div[4]/input</value>
      <webElementGuid>ba2534a0-2ffa-4f95-b818-b40893e81213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'isActive' and @id = 'isActiveAdd']</value>
      <webElementGuid>a3cf434f-7e88-4676-99d7-50d59380a0b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
