<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Instansi_instanceCode</name>
   <tag></tag>
   <elementGuidId>69179031-0bc6-4f40-a3e2-9ade1625d4a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kodeInstansiAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kodeInstansiAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73409d48-c777-4494-bb65-2f1e9158200e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d417f75-dac6-4bf0-93b9-38c11274b3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>634290ad-ce79-4917-a527-8826e5ea5add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kodeInstansiAdd</value>
      <webElementGuid>9fe91907-d72d-4ab6-b3bb-25ef1555f3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instanceCode</value>
      <webElementGuid>bc2f8c0b-578c-4555-aad6-86b594c8a95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Instansi</value>
      <webElementGuid>aaeb7f93-84f3-4e83-ab9c-f57dd72ad82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c8b74926-81dd-49ca-9aca-0fd0cfb42d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kodeInstansiAdd&quot;)</value>
      <webElementGuid>d3cbbe1c-c485-435d-97c4-ad2d1da7f034</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kodeInstansiAdd']</value>
      <webElementGuid>38ccc214-d6d4-4e08-a2e0-da16aed3a01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/input</value>
      <webElementGuid>0a8ab8ff-6e9f-4c1a-8e07-fa81ed97162f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>4a2ff405-2cca-4921-b9e6-1349d79368ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kodeInstansiAdd' and @name = 'instanceCode' and @placeholder = 'Kode Instansi']</value>
      <webElementGuid>074b42dc-b9a5-4c31-88f2-f9afa8900c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
