<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_fe-eye</name>
   <tag></tag>
   <elementGuidId>34cb3163-3698-418e-9f6f-df806747ac3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fe-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9549dd56-9083-4e29-8ac3-8f260b114d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fe-eye</value>
      <webElementGuid>aadde766-f5a4-4e1f-a226-eec18737b024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showPasswordLogin&quot;)/span[@class=&quot;fe-eye&quot;]</value>
      <webElementGuid>fa17c576-6f82-4aa5-bdc6-52e82cde39a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='showPasswordLogin']/span</value>
      <webElementGuid>2fd0a643-108f-49e0-b31b-5b0efc96662c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>6e0b8266-eec6-47ae-9dc8-4c18ed24c7f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
