<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find by Transaction ID_criteria.trans_18ad5c</name>
   <tag></tag>
   <elementGuidId>bfdf0680-4450-4eb3-9590-b06c2fe7df0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='criteria.transactionId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99230a2e-be07-436a-aadd-6dc4c0596ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>criteria.transactionId</value>
      <webElementGuid>142f4ad1-e965-4be3-ac23-84c74504e8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-empty ng-valid-required</value>
      <webElementGuid>a674faf8-a8be-4d2c-9bcd-58122a6fef64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>criteria.transactionId</value>
      <webElementGuid>ed0c4b99-3187-4e4d-85c3-89580c9b3e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>criteria.searchType === 'ID'</value>
      <webElementGuid>66377002-4e99-44c3-90e9-5e9b31948dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;criteria.transactionId&quot;)</value>
      <webElementGuid>af3c4c1c-61c7-4c95-847b-4e4d9f4ded50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='criteria.transactionId']</value>
      <webElementGuid>6427a60a-df93-4cd5-a185-65da329dee10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/div[2]/input</value>
      <webElementGuid>35882732-a423-437c-9ef4-66059f863ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8c5dc002-e0c7-4f21-8f32-1c986577ea7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'criteria.transactionId']</value>
      <webElementGuid>0a11cfa1-8b09-44af-bd70-d57f3cd8b6de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
