<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find by Date_criteria.onDate</name>
   <tag></tag>
   <elementGuidId>564669fc-e7a6-4467-a4f9-787920f8bee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='criteria.onDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64864a95-bbce-4e9c-8c2d-0b17d565ac70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>criteria.onDate</value>
      <webElementGuid>c29206a6-d6ce-4ffe-8ff4-638f6bc29f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-empty ng-valid-required</value>
      <webElementGuid>f5c045ca-34ef-493b-ac54-e68b26fef60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>criteria.onDate</value>
      <webElementGuid>ddd49958-f9e8-48e8-b9fc-e5d390c1d85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>criteria.searchType === 'DATE'</value>
      <webElementGuid>75e9414b-fd5f-47db-930b-6cdc23dda38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;criteria.onDate&quot;)</value>
      <webElementGuid>c683fc56-4728-4192-85f8-57c4f38851e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='criteria.onDate']</value>
      <webElementGuid>9395b7d8-b489-4790-b54b-ae01f89b4b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/div[4]/input</value>
      <webElementGuid>42aafb5a-2821-4eca-b77b-8450179c8a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>399cfe96-0286-41e4-85f6-bc8139b6e861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'criteria.onDate']</value>
      <webElementGuid>976644c6-26bd-4241-aa5d-0e9f922fdd79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
