<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_5000.00</name>
   <tag></tag>
   <elementGuidId>047433f6-d6fd-4274-906f-c5185329cf9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='accountTable']/tbody/tr[3]/td[2]/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>23877f6c-ee86-4f08-a243-f490a4d9bbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>0ec83e20-9328-4492-a0c0-13d61ad58ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$5000.00</value>
      <webElementGuid>9a09965d-c993-4dae-a753-d0bbd7bb0dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountTable&quot;)/tbody[1]/tr[3]/td[2]/b[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>865f4d94-5831-413b-8546-839e76c6864d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='accountTable']/tbody/tr[3]/td[2]/b</value>
      <webElementGuid>9b5e041d-8fbb-4631-9e92-16bef18522cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/b</value>
      <webElementGuid>c768fe0e-517e-4762-a2b9-008ec1beaa62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '$5000.00' or . = '$5000.00')]</value>
      <webElementGuid>b50457f2-3424-4147-b9cb-dabd014cb74b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
