<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Choose Level --</name>
   <tag></tag>
   <elementGuidId>bc01736e-52f3-428c-a5d5-af7a612a47c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-levelAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-levelAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6911bcfd-e31c-4457-914b-771c96d40f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>41ddaca3-bdbd-4cae-af1a-bf2d2b36e97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-levelAdd-container</value>
      <webElementGuid>a0eacae9-50e3-46df-9667-bd94db8b28be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Level 1</value>
      <webElementGuid>e526d0e6-6bf0-4419-9341-6482a894bb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Level --</value>
      <webElementGuid>7f705739-4de5-4197-8ad7-7fa98abe31b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-levelAdd-container&quot;)</value>
      <webElementGuid>e50b4a0e-37bd-4fe4-bb70-97fe609243ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-levelAdd-container']</value>
      <webElementGuid>704a2fe0-b1cc-4ce4-b95c-ce52879c2e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/div/div/span/span/span/span</value>
      <webElementGuid>8728d70e-102c-4939-bb87-db69ba8d83fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level *'])[1]/following::span[4]</value>
      <webElementGuid>2c9789e3-99ee-4eb2-b267-e691e249d023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Question'])[2]/following::span[4]</value>
      <webElementGuid>e257c521-ce51-402f-95f4-451630c5a640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module *'])[1]/preceding::span[4]</value>
      <webElementGuid>60ed0fe6-20cd-4f67-b362-05820cdb0034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>3d646ec0-3700-49e5-9eb8-b47a808be3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-levelAdd-container' and @title = 'Level 1' and (text() = '-- Choose Level --' or . = '-- Choose Level --')]</value>
      <webElementGuid>e3e9d05f-238a-42ee-9879-54116bbade09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
