<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Choose Module --</name>
   <tag></tag>
   <elementGuidId>41d736f9-19b3-48e3-b204-6bbf588cfbd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-moduleAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-moduleAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f2a289fc-4475-441e-ac6e-a1acc59124b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>24aa5bb1-0910-4025-8950-5ffad2084da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-moduleAdd-container</value>
      <webElementGuid>c9a72636-dc43-43a8-a51b-d947df6bf94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Module 1</value>
      <webElementGuid>f0fa3170-86f8-41e3-a320-b1813773de5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Module --</value>
      <webElementGuid>699dfdd4-d044-4725-9e93-fa6cd7c87396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-moduleAdd-container&quot;)</value>
      <webElementGuid>6d9b5b68-51b2-4a9a-9446-7b126c31126b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-moduleAdd-container']</value>
      <webElementGuid>3da51c4f-a98c-4cbd-a470-2f83ac5f7e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>e0e35ef0-5ddd-4347-8e7d-7f91dcfaea35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module *'])[1]/following::span[4]</value>
      <webElementGuid>3e67e9ed-2ef6-499d-aac9-bbbaf4b0abb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Choose Level --'])[1]/following::span[6]</value>
      <webElementGuid>3ddd9b59-4210-41d4-88f0-31a41ee96281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chapter *'])[1]/preceding::span[4]</value>
      <webElementGuid>ed36bb2b-bd80-4ba7-99a9-c3df317795e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>b9767027-ccef-4cf6-a527-6dc84a4fe07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-moduleAdd-container' and @title = 'Module 1' and (text() = '-- Choose Module --' or . = '-- Choose Module --')]</value>
      <webElementGuid>5d7781e4-6cb4-458e-b92d-4f549418a714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
